# Generated by Django 4.2 on 2023-06-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код камеры')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Камеры')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Доп онфо о камере')),
                ('position', models.IntegerField(default=0, verbose_name='Расположение')),
                ('total_cells', models.IntegerField(default=0, verbose_name='Количество ячеек')),
                ('empty_cells', models.IntegerField(default=0, verbose_name='Количество пустых ячеек')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CameraAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя атрибюта')),
            ],
            options={
                'verbose_name': 'Аттрибют Камеры',
                'verbose_name_plural': 'Аттрибюты Камеры',
            },
        ),
        migrations.CreateModel(
            name='CellAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя атрибюта')),
            ],
            options={
                'verbose_name': 'Аттрибют Ячейки',
                'verbose_name_plural': 'Аттрибюты Ячейки',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код ряда')),
                ('position', models.IntegerField(default=0, verbose_name='Расположение')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_row', to='stock.camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Ряд',
                'verbose_name_plural': 'Ряды',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код столбца')),
                ('position', models.IntegerField(default=0, verbose_name='Расположение')),
                ('row_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_column', to='stock.row', verbose_name='Ряд')),
            ],
            options={
                'verbose_name': 'Столбец',
                'verbose_name_plural': 'Столбцы',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код ячейки')),
                ('position', models.IntegerField(default=0, verbose_name='Расположение')),
                ('is_full', models.BooleanField(default=False, verbose_name='Наполненный?')),
                ('column_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_cell', to='stock.column', verbose_name='Столбец')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_product', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CellCellAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Величина')),
                ('cell_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_cell_attribute', to='stock.cellattribute', verbose_name='Аттрибют чейки')),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_attribute', to='stock.cell', verbose_name='Ячейка')),
            ],
            options={
                'verbose_name': 'Значения Аттрюбютов Ячейки',
                'verbose_name_plural': 'Значении Аттрюбютов Ячейки',
                'unique_together': {('cell_id', 'cell_attribute_id')},
            },
        ),
        migrations.CreateModel(
            name='CameraCameraAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Величина')),
                ('camera_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_camera_attribute', to='stock.cameraattribute', verbose_name='Аттрибют Камеры')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_attribute', to='stock.camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Значения Аттрюбютов Камеры',
                'verbose_name_plural': 'Значении Аттрюбютов Камеры',
                'unique_together': {('camera_id', 'camera_attribute_id')},
            },
        ),
    ]
