# Generated by Django 4.2 on 2023-07-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('batch', '0002_alter_batch_options_alter_pallet_is_placed'),
        ('stock', '0004_alter_cell_pallet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_full', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_cell_log', to='stock.cell')),
                ('pallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_cell_log', to='batch.pallet')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cell_log', to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
