# Generated by Django 4.2 on 2023-07-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_alter_batch_options_alter_pallet_is_placed'),
        ('product', '0001_initial'),
        ('stock', '0005_celllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celllog',
            name='pallet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pallet_cell_log', to='batch.pallet'),
        ),
        migrations.AlterField(
            model_name='celllog',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cell_log', to='product.product'),
        ),
    ]
