# Generated by Django 4.2 on 2023-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_celllog_pallet_id_alter_celllog_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celllog',
            name='created_at',
            field=models.DateField(),
        ),
    ]
