# Generated by Django 4.2 on 2023-06-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Код продукта')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя продукта')),
                ('qrcode', models.ImageField(default='qrcodes/default.jpg', upload_to='qrcodes/', verbose_name='QR код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Доп инфо продукта')),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products/', verbose_name='Фото')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя аттрибюта')),
            ],
            options={
                'verbose_name': 'Аттрибют продукта',
                'verbose_name_plural': 'Аттрибюты продуктов',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя единицы')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_value', to='product.product', verbose_name='Продукт')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_value', to='product.unit', verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Количество Продукта',
                'verbose_name_plural': 'Количество Продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_unit', to='product.unit', verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='ProductProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('product_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_attr_value', to='product.productattribute', verbose_name='Аттрибют')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attr_value', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Значение Аттрибюта продукта',
                'verbose_name_plural': 'Значении Аттрибютов продукта',
                'unique_together': {('product_id', 'product_attribute_id')},
            },
        ),
    ]
