# Generated by Django 4.2 on 2023-07-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlog',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='productlog',
            name='created_at',
            field=models.DateField(),
        ),
    ]
