# Generated by Django 4.2 on 2023-06-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'ordering': ['arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Аттрибют Партии',
                'verbose_name_plural': 'Аттрибюты Партии',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('id_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер')),
                ('type_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('pallet_count', models.IntegerField(default=0, verbose_name='Количество Паллетов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обнавлено в')),
            ],
            options={
                'verbose_name': 'Кантейнер',
                'verbose_name_plural': 'Кантейнеры',
            },
        ),
        migrations.CreateModel(
            name='ContainerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя аттрибюта')),
            ],
            options={
                'verbose_name': 'Аттрибют Контейнера',
                'verbose_name_plural': 'Аттрибюты Контейнеров',
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код паллета')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Доп инфо')),
                ('is_placed', models.BooleanField(default=False, verbose_name='Рзместен?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен?')),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnt_pallet', to='batch.container', verbose_name='Контейнер')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pallet', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Паллет',
                'verbose_name_plural': 'Паллеты',
            },
        ),
        migrations.CreateModel(
            name='PalletAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя аттрибюта')),
            ],
            options={
                'verbose_name': 'Аттрибют Паллета',
                'verbose_name_plural': 'Аттрибюты Паллета',
            },
        ),
        migrations.CreateModel(
            name='PalletPalletAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Величина')),
                ('pallet_attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_pallet_value', to='batch.palletattribute', verbose_name='Палет Аттрибют')),
                ('pallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_attr_value', to='batch.pallet', verbose_name='Паллет')),
            ],
            options={
                'verbose_name': 'Значение Аттрибютов Паллета',
                'verbose_name_plural': 'Значении Аттрибютов Паллетов',
                'unique_together': {('pallet_id', 'pallet_attr_id')},
            },
        ),
        migrations.CreateModel(
            name='ContainerContainerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('container_attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_cnt_value', to='batch.containerattribute', verbose_name='Аттрибют контейнера')),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnt_attr_value', to='batch.container', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Величина Аттрибюта Контейнера',
                'verbose_name_plural': 'Величины Аттрибюта Контейнера',
                'unique_together': {('container_id', 'container_attr_id')},
            },
        ),
        migrations.CreateModel(
            name='BatchContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_cnt', to='batch.batch', verbose_name='Партия')),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnt_batch', to='batch.container', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Контейнер Партии',
                'verbose_name_plural': 'Контейнеры Партии',
                'unique_together': {('batch_id', 'container_id')},
            },
        ),
        migrations.CreateModel(
            name='BatchBatchAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Величина')),
                ('batch_batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_attribute_value', to='batch.batchattribute', verbose_name='Аттрибют')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_value', to='batch.batch', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Величина Аттрибюта Партии',
                'verbose_name_plural': 'Величины Аттрибютов Партии',
                'unique_together': {('batch_id', 'batch_batch_id')},
            },
        ),
    ]
