# Generated by Django 4.2 on 2023-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-arrived_at'], 'verbose_name': 'Партия', 'verbose_name_plural': 'Партии'},
        ),
        migrations.AlterField(
            model_name='pallet',
            name='is_placed',
            field=models.BooleanField(default=False, verbose_name='Разместен?'),
        ),
    ]
