from django.urls import path

from . import views

# Ендпоинты для Партии
urlpatterns = [
    path('batch-list/', views.BatchListView.as_view(), name='batch-list'),
    path('batch-detail/<int:pk>/', views.BatchDetailView.as_view(), name='batch-detail'),
    path('batch-attribute-list/', views.BatchAttributeListView.as_view(), 
         name='batch-attribute-list'),
    path('batch-attribute-create/', views.BatchAttributeCreateView.as_view(),
         name='batch-attribute-create'),
    path('batch-attribute-update/<int:pk>/', views.BatchAttributeUpdateView.as_view(),
         name='batch-attribute-update'),
    path('bb-attr-create/', views.BBAttrCreateView.as_view(), 
         name='bb-attr-create'),
    path('bb-attr-update/<int:pk>/', views.BBAttrUpdateView.as_view(),
         name='bb-attr-update'),
    path('container-list/', views.ContainerListView.as_view(), name='container-list'),
    path('container-create/', views.ContainerCreateView.as_view(),
         name='container-create'),
    path('container-update-delete/<int:pk>/', views.ContainerUpdateDeleteView.as_view(),
         name='container-update-delete'),
    path('cnt-attributes-list/', views.CntAttrListView.as_view(),
         name='cnt-attributes-list'),
    path('cnt-attr-create/', views.CntAttrCreateView.as_view(), 
         name='cnt-attr-create'),
    path('cnt-attr-update-delete/<int:pk>/', views.CntAttrUpdateDeleteView.as_view(),
         name='cnt-attr-update-delete'),
    path('cc-attr-create/', views.CntCntAttrCreateView.as_view(),
         name='cc-attr-create'),
    path('cc-attr-update-delete/<int:pk>/', views.CntCntAttrUpdateDeleteView.as_view(),
         name='cc-attr-update-delete'),
    path('batch-container-create/', views.BatchContainerCreateView.as_view(),
         name='batch-container-create'),
    path('batch-container-update-delete/<int:pk>/', views.BatchContainerUpdateDeleteView.as_view(),
         name='batch-container-update-delete'),
    path('pallet-list/', views.PalletListView.as_view(), name="pallet-list"),
    path('pallet-detailed-list/', views.PalletDetailedListView.as_view(), 
         name='pallet-detailed-list'),
    path('pallet-create/', views.PalletCreateView.as_view(), name="pallet-create"),
    path('pallet-detail/<int:pk>/', views.PalletDetailView.as_view(),
         name="pallet-detail"),
    path('pallet-attr-list/', views.PalletAttributeList.as_view(), 
         name='pallet-attr-list'), 
    path('pallet-attr-create/', views.PalletAttributeCreate.as_view(),
         name='pallet-attr-create'), 
    path('pallet-attr-update/<int:pk>/', views.PalletAttributeUpdate.as_view(),
         name='pallet-attr-update'),
    path('pp-attribute-create/', views.PalletPAttributeCreate.as_view(),
         name='pp-attribute-create'),
    path('pp-attr-update-delete/<int:pk>/', views.PalletPAttributeUDView.as_view(),
         name='pp-attr-ud'),
]