from django.urls import path

from . import views

# Ендпоинты для Партии
urlpatterns = [
    path('pc-transfer-list/', views.PCTransferListView.as_view(), 
         name='pc-transfer-list'),
    path('pc-transfer-create/', views.PCTransferCreateView.as_view(),
         name='pc-transfer-create'),
    path('pc-transfer-detail/<int:pk>/', views.PCTransferDetailView.as_view(),
         name='pc-transfer-detail'),
    path('pc-transfer-update-delete/<int:pk>/', views.PCTransferUDView.as_view(),
         name='pc-transfer-update-delete'),
    path('transfer-attributes/', views.TransferAttributeListView.as_view(),
         name='transfer-attributes'),
    path('transfer-attr-create/', views.TransferAttrCreateView.as_view(),
         name='transfer-attr-create'),
    path('transfer-attr-update/<int:pk>/', views.TransferAttrUpdate.as_view(),
         name='transfer-attr-update'),
    path('transfer-attr-value-create/', views.TTransferAttrCreateView.as_view(),
         name='transfer-attr-value-create'),
    path('transfer-attr-value-update/<int:pk>/', views.TTransferAttrUDView.as_view(),
         name='transfer-attr-value-update'),
    path('pallet-cell-transfer-list/', views.PalletCellTransferListView.as_view(),
         name='pallet-cell-transfer-list'),
    path('pallet-cell-transfer-create/', views.PalletCellTransferCreateView.as_view(),
         name='pallet-cell-transfer-create'),
    path('pallet-cell-transfer-update/<int:pk>/', views.PalletCellTransferUpdateView.as_view(),
         name='pallet-cell-transer-update'),
    path('pallet-cell-transfer-delete/<int:pk>/', views.PalletCellTransferDeleteView.as_view(),
         name='pallet-cell-transfer-delete'),
    path('pallet-transfer-paginated-list/', views.PalletTransferPaginatedListView.as_view(),
         name='pallet-transfer-paginated-list'),
    path('pallet-transfer-create/', views.PalletTransferCreateView.as_view(),
         name='pallet-transfer-create'),
    path('pallet-transfer-detail/<int:pk>/', views.PalletTransferDetailView.as_view(),
         name='pallet-transfer-detail'),
    path('pallet-transfer-update/<int:pk>/', views.PalletTransferUpdateView.as_view(),
         name='pallet-transfer-update'),
    path('pallet-transfer-delete/<int:pk>/', views.PalletTransferDeleteView.as_view(),
         name='pallet-transfer-delete'),
    path('pallet-reduce-paginated-list/', views.PalletReducePaginatedListView.as_view(),
         name='pallet-reduce-paginated-list'),
    path('pallet-reduce-create/', views.PalletReduceCreateView.as_view(),
         name='pallet-reduce-create'),
    path('pallet-reduce-update/<int:pk>/', views.PalletReduceUpdateView.as_view(),
         name='pallet-reduce-update'),
    path('pallet-reduce-delete/<int:pk>/', views.PalletReduceDeleteView.as_view(),
         name='pallet-reduce-delete'),
    path('pallet-reduce-detail/<int:pk>/', views.PalletReduceDetailView.as_view(),
         name='pallet-reduce-detail'),
]