# Generated by Django 4.2 on 2023-06-14 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_type', models.CharField(choices=[('Поступление', 'Поступление'), ('Отправление', 'Отправление')], default='Поступление', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обнавлено в')),
                ('batch_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_batch', to='batch.batch', verbose_name='Партия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pct_user_transfer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Трансакция',
                'verbose_name_plural': 'Трансакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Аттрибют Трансакции',
                'verbose_name_plural': 'Аттрибюты Трансакции',
            },
        ),
        migrations.CreateModel(
            name='PalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обнавлено в')),
                ('in_cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pct_in_cell', to='stock.cell', verbose_name='Входящее Ячейка')),
                ('out_cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pct_out_cell', to='stock.cell', verbose_name='Исходящее Ячейка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_user_transfer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Перемещение Содержимых ячейки',
                'verbose_name_plural': 'Перемещении Содержимых ячеек',
            },
        ),
        migrations.CreateModel(
            name='PalletReduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
                ('reason', models.CharField(default='Порча', max_length=255, verbose_name='Причина')),
                ('image', models.ImageField(default='reduce/default.jpg', upload_to='reduce/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Подробнее')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обнавлено в')),
                ('pallet_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduce_attribute', to='batch.palletattribute', verbose_name='Аттрибют паллета')),
                ('pallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_reduce', to='batch.pallet', verbose_name='Паллет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reduce', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уменьшение в Паллете',
                'verbose_name_plural': 'Уменьшение в Паллетах',
            },
        ),
        migrations.CreateModel(
            name='TransferTransferAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Величина')),
                ('pctransfer_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_attribute_value', to='transfer.transferattribute', verbose_name='Аттрибют')),
                ('pctransfer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_value', to='transfer.pctransfer', verbose_name='Трансакция')),
            ],
            options={
                'verbose_name': 'Величина Аттрибюта Трансакции',
                'verbose_name_plural': 'Величины Аттрибютов Трансакции',
                'unique_together': {('pctransfer_id', 'pctransfer_attribute_id')},
            },
        ),
        migrations.CreateModel(
            name='PalletCellTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_transfer', to='stock.cell', verbose_name='Ячейка')),
                ('pallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_transfer', to='batch.pallet', verbose_name='Паллет')),
                ('transfer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_transfer', to='transfer.pctransfer', verbose_name='Трансакция')),
            ],
            options={
                'verbose_name': 'Ячейка Трансакции',
                'verbose_name_plural': 'Ячейки Трансакции',
                'unique_together': {('pallet_id', 'transfer_id')},
            },
        ),
    ]
