# Generated by Django 4.2 on 2023-06-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pctransfer',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='exl/batch/'),
        ),
    ]
