# Generated by Django 4.2 on 2023-06-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_pctransfer_excel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pctransfer',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
